"""create service_orders

Revision ID: 9dd7d07ad5a5
Revises: 877303562b66
Create Date: 2026-06-18 01:54:36.508213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd7d07ad5a5'
down_revision: Union[str, Sequence[str], None] = '877303562b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('equipment_type', sa.String(length=500), nullable=False),
    sa.Column('reported_problem', sa.String(length=2000), nullable=False),
    sa.Column('equipment_brand', sa.String(length=255), nullable=True),
    sa.Column('equipment_model', sa.String(length=255), nullable=True),
    sa.Column('equipment_identification', sa.String(length=255), nullable=True),
    sa.Column('internal_notes', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_orders_customer_id', 'service_orders', ['customer_id'], unique=False)
    op.create_index('ix_service_orders_status', 'service_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_orders_status', table_name='service_orders')
    op.drop_index('ix_service_orders_customer_id', table_name='service_orders')
    op.drop_table('service_orders')
    # ### end Alembic commands ###
